name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8.x SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore & Build Shared
        run: |
          dotnet restore ./Shared/Shared.csproj
          dotnet build ./Shared/Shared.csproj -c Release --nologo

      - name: Restore & Build Server.Library
        run: |
          dotnet restore ./Server/Server.Library.csproj
          dotnet build ./Server/Server.Library.csproj -c Release --nologo

      - name: Restore & Build Server.MirForms (GUI)
        run: |
          dir .\Components\
          dotnet restore ./Server.MirForms/Server.csproj
          dotnet build ./Server.MirForms/Server.csproj -c Release --nologo
